[package]
name = "nexacode-desktop"
version = "0.1.0"
description = "NexaCode - A desktop application built with Tauri + React"
authors = ["NexaCode"]
license = "MIT"
repository = "https://github.com/fansili/NexaCode"
edition = "2021"
rust-version = "1.77.2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "nexacode_desktop_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.6.1", features = [] }

[dependencies]
nexacode-core = { path = "../nexacode-core" }
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
log = "0.4"
tauri = { version = "2.11.1", features = [] }
tauri-plugin-log = "2"
tokio = { version = "1", features = ["full"] }
futures = "0.3"
anyhow = "1.0"
dirs = "5.0"
toml = "0.8"
